#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

banner "Tiptap Server AI Toolkit — Bubble smoke test"

REPO_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
PLUGIN_EDITOR_URL="https://bubble.io/plugin_editor?id=1670612027178x122079323974008830"
EXPECTED_CDN_URL="https://meta-q.cdn.bubble.io/f1786956454280x489830055410652900/dist.js"
EXPECTED_SHA256="022b83cf84ac710dedbc02c34c38c5a5497adb216f3bb51749bbe76ddcdfb3f9"

stage "Verify the deployed artifact"
cd "$REPO_ROOT"
step "Checking that Bubble and the local Pled source are in sync."
if command -v pled >/dev/null 2>&1 && pled check-remote; then
  say "Bubble source is in sync."
else
  warn "Pled could not verify sync. Confirm BUBBLE_COOKIE and run: pled check-remote"
fi
step "Checking the exact JavaScript bundle uploaded for this test."
REMOTE_SHA=$(curl -fsSL "$EXPECTED_CDN_URL" | { command -v sha256sum >/dev/null 2>&1 && sha256sum || shasum -a 256; } | awk '{print $1}')
if [[ "$REMOTE_SHA" != "$EXPECTED_SHA256" ]]; then
  warn "CDN checksum mismatch: expected $EXPECTED_SHA256, got $REMOTE_SHA"
  exit 1
fi
say "CDN checksum matches: $REMOTE_SHA"
pause "Artifact verified. Press Enter to configure the Bubble test app."

stage "Configure Tiptap credentials"
open_url "$PLUGIN_EDITOR_URL"
say "Use a Bubble test app that has this development plugin installed."
ask BUBBLE_APP_EDITOR_URL "Paste the Bubble test app editor URL:"
open_url "$BUBBLE_APP_EDITOR_URL"
step "Open Plugins → Rich Text Editor (Tiptap.dev) → settings."
step "Set 'Tiptap AI environment ID' to your Tiptap Access Control environment ID."
step "Set 'Tiptap AI ES256 private key' to its PKCS#8 P-256 private key."
step "Leave 'Tiptap AI API base URL' empty for https://api.tiptap.dev."
warn "Never put the private key in an element property, page state, workflow input, or browser code."
pause "Press Enter after saving the plugin settings."

stage "Test editor-context lifecycle"
step "Create/open a test page and add a Tiptap element."
step "Set initial content to <p>Hello AI Toolkit</p> and enable the element's 'AI Toolkit' checkbox."
step "Add text elements showing: Tiptap's AI editor context, AI context error, and content JSON states."
step "Add workflows for 'AI editor context ready' and 'AI editor context failed' (show an alert or set a page state)."
step "Add a button whose workflow runs the element action 'Refresh AI editor context'."
step "Preview the page. Expect valid JSON with serializedSchema/items, an empty error, and one ready event."
step "Click Refresh. Expect another ready event and stable JSON. Temporarily disable AI Toolkit and refresh; expect the failed event and compatibility warning."
pause "Press Enter when the context lifecycle behaves as expected."

stage "Fetch an explicit tool allowlist"
step "Re-enable AI Toolkit, wait for the ready event, and add a 'Fetch tools' button."
step "Its workflow runs the server action 'Fetch AI Toolkit tools'."
step "Set AI editor context (JSON) to the editor's AI editor context state."
step "Set Tool allowlist to: tiptapRead,tiptapEdit"
step "Store or display the action result's success, status code, error code, error message, system prompt, and tool definitions JSON."
step "Preview and click it. Expect success=yes, status=200, and definitions for exactly tiptapRead and tiptapEdit."
step "Repeat with an empty allowlist; expect no tools. Repeat with deleteEverything; expect error_code=unsupported_tool and no network success."
pause "Press Enter when fetch-tools passes."

stage "Execute an inline read"
step "Add an 'Execute inline read' button using 'Execute AI Toolkit tool'."
step "AI editor context: the editor's AI editor context state."
step 'Tool call JSON: {"name":"tiptapRead","input":{"from":0}}'
step "Document mode: Inline. Inline document JSON: the editor's content JSON state."
step "Display success, status code, error fields, tool output JSON, document changed, and updated inline document JSON."
step "Preview and click it. Expect success=yes, status=200, tiptapRead output containing the document, and document changed=no."
step "For an LLM-generated tiptapEdit call, pass its name/input JSON to the same action. When document changed=yes, run the existing Set content action with updated inline document JSON and Is JSON?=yes."
warn "If the user edited while the request was running, decide whether to confirm/retry instead of blindly replacing their newer content."
pause "Press Enter when inline execution passes."

stage "Optional collaborative test and result"
step "If testing collaboration, connect the editor to a Tiptap Cloud document using its existing collaboration settings."
step "Run Execute AI Toolkit tool with mode Collaborative, the exact cloud document ID, and the same tiptapRead call."
step "Expect success=yes. For tiptapEdit, do not call Set content; verify the existing collaboration provider delivers the edit."
step "A different document ID must not be authorized by the token minted for this call. All clients on one document must use the same schema/AI Toolkit setting."
step "Check Bubble server logs only for status/errors; the private key and bearer token must never appear."
say "Pass criteria: context lifecycle, explicit fetch allowlist, inline read, structured failures, and (if configured) collaborative sync all behave as described."

finish
